### ISSUE TITLE
irksome error message in editor

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#1015]
![image](https://cloud.githubusercontent.com/assets/11738011/19195334/90159708-8c87-11e6-9772-27718df91ea5.png)

i suspect this error is related to errors in projects (files moved, renamed, etc). 

now, ocurs me when save files.
in other ocassions, ocurs while typing, but cant reproduce it

**Comment by fdodino** [comment]
Yes, it is irksome (hahah, I had to look its definition).

I've been struggling with this all weekend. It  is a classpath problem refreshing a wollk file (test, program) from wollok.ui.launch instead of wollok.launch, which can find wollok lib files. I still don't know if we can solve it by
- using "platform:/resource" to load wollok file from refactor, quick fix, etc.
- or adding wollok libs files (lang.wlk, lib.wlk) from wollok.ui.launch.
Maybe neither of them
:smile:

**Comment by fdodino** [comment]
Related to #912

**Comment by fdodino** [comment]
Ok, problem is here

ClassloaderClasspathUriResolver.findResourceOnClasspath - line 59 for resources beginning with "classpath:". 

Instead of using
org.eclipse.xtext.ui.util.JdtClasspathUriResolver
that resolves perfectly in XTextResourceSet:
URI result = XtextResourceSet.this.resolveClasspathURI(uri);

When you open a lib.wlk or lang.wlk, it uses ClassloaderClasspathUriResolver that leads to that error.
I was working on another branch, but in order to show hyperlinks to files I came to this.
For now I put a cache, so we're not loading n times wlk classpath files, and it opens very fast a lib.wlk
But if you close IDE and start it again, error appears again.

**Comment by fdodino** [comment]
Ah, ah, ah...

```java
    public IClasspathUriResolver getClasspathUriResolver() {
        if (resolver == null) {
            resolver = new ClassloaderClasspathUriResolver();
        }
        return resolver;
    }
```

here, in XTextResourceSet.class, resolver is null (is not injected).

**Comment by fdodino** [comment]
Well, this moment could be named "Breaking bad".
This morning I got a working solution.
I was so happy.
But... a few hours later nothing worked. Eclipse failed. Unit tests failed. And Wollok Tests in IDE didn't launch at all. Several classpath errors appeared in Wollok Console (instead of Developer Console).

I'll describe my solution and I guess why did it happen, just in case @javierfernandes or @tesonep have any better ideas.
Last night I put a cache of resources (and then exportedObjects) that came with wollok library classpath files (such as lang.wlk, lib.wlk) because they do not change at all during IDE execution

So, if you tried to open (F3) assert object in a test method, it worked like a charm, because test.wtest found every .wlk library file in classpath because it used JdtClasspathUriResolver. So I cached this resource, and then I could reuse it for editor.

The only situation I had to solve was, if you opened a lib.wlk and close every wtest or developed wlk (not a library wlk but a example.wlk or similar), the classpath resolver for that was ClassloaderClasspathUriResolver, and classpath context was null, so it couldn't find lang.wlk or lib.wlk in classpath. For that, I tried to rescue a Java Project and replace ClassloaderClasspathUriResolver with JdtClasspathUriResolver. So... the problem is that I'm in a wollok project, not wollok.ui.launch, so IJavaProject and IProject sometimes doesn't get loaded by classloader, and it breaks the entire IDE.

I pushed a branch: classpath-files-loading.
It would be very useful if you take a look and give me some fresh ideas.
For now I could run all tests and it passes ok.
It is a workaround for nearly 90% of situations, but I would prefer to catch the 10%  :smile:

**Comment by tesonep** [comment]
Have you fix it? Or just give up? Or you closed it by error?

**Comment by fdodino** [comment]
Last night we were talking with @Juancete and @lspigariol and realized that possibly this issue was related to Xpect test errors

* initially when LRUMap was introduced in WollokGlobalScopeProvider Xpect test errors appeared
* and also this problem, that was mainly because of dependencies between wollok.ui.launch and wollok (I don't remember it well)
* there was also a similar problem when opening a wollok library file in editor (like lib.wlk or lang.wlk), closing IDE and opening IDE again. Only in plugin development mode (when you run with plugin.xml). It didn't happen when running final product (I think mainly related with order in which dependencies were activated). 

I can't be 100% sure, but using a new cache for library files like lang & lib.wlk apparently solved this and other issues. I couldn't create a test case, since it is not so a "unit test" but an integration test indeed.

So, my position is to close this issue and reopen if it happens again.

**Comment by tesonep** [comment]
The issues that you can close without changing a thing are the one I like.
:-)

**Comment by fdodino** [comment]
:+1: :smile:

**Comment by lspigariol** [comment]
thanks! good job. 
I also looked it up in the dictionary
