### ISSUE TITLE
Date today - object "now"

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#1029]
I'd like some way to get today's date.

Thinking a bit about it, I got to this:

I'd really much like to have an object like "now", for example, in order to ask it several things:

```wollok
now.date() // returns today's date
now.year() // returns the year (integer)
now.time() // Oh, I think Wollok doesn't have Time... Yikes, I need to open another issue.
now.mockDay(d,m,y) // mocks today's date, only works in tests
//etc.
```

It could also have shortcuts to Date's methods, like `now.dayOfWeek()`.

Thoughts on this?

**Comment by matifreyre** [comment]
Dates have 2 constructors:
- with 3 parameters (day, month, year)
- with no parameters, which creates a date using the system date.

I guess that covers your needs :)

**Comment by asanzo** [comment]
![92acad61-c990-638a-ad90dd36016599ee](https://cloud.githubusercontent.com/assets/5421992/19546670/18999892-9668-11e6-9a92-32b5b420c86e.jpg)

**Comment by npasserini** [comment]
Yet Mati is right, I like Alf's idea, using now instead of new Date() seems
more natural, what do you think?

The problem is that now would not be a stable object, i.e. each time I use
it, it represents a different date, which is not true for other Date
objects... so if we do that we should think that now is not a date, but
another kind of object... posibly polymorphic for some uses.

I am not sure if it is going to be easy to understand.

2016-10-20 6:54 GMT+02:00 asanzo <notifications@github.com>:
