### ISSUE TITLE
Automatic software updates do not work

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#197]
![image](https://cloud.githubusercontent.com/assets/4633913/9423846/257cf9ec-48ac-11e5-8c64-c6797273d3a8.png)

**Comment by tesonep** [comment]
The master branch build has an error in the pom and was only updating the products. The problem is that I can see the repo, I don't get the same error, only in the Update Site there are old versions.

Can you try again if you can see the repository (once the build is over), maybe is a problem of network or a problem of unavailable server.
