### ISSUE TITLE
[community] Add wollok language detection to GitHub

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#298]
I think that we need to create a PR like this one

https://github.com/github/linguist/pull/2634/files

Actually I think that it uses the same format as Sublime, so we can think of reusing the grammar that we did for Sublime

**Comment by javierfernandes** [comment]
Created this PR

https://github.com/github/linguist/pull/2678

**Comment by fdodino** [comment]
I did a ping recently.

**Comment by fdodino** [comment]
They approved us only for wlk files (at least...) 
We must wait for wtest until we have more repositories (this year it will be easy to achieve as we are moving from SVN to git)
Added a new PR...
https://github.com/github/linguist/pull/3762

**Comment by fdodino** [comment]
Well, I  had to fork github repository again because I copied some files without running the scripts [as I should](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) so a new PR was added: https://github.com/github/linguist/pull/3764

Added a color definition (same as sidebar site)

**Comment by fdodino** [comment]
Closing this as we already achieved that.
