### ISSUE TITLE
Extract method shortcut is not working

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#313]
CMD+SHIFT+M ?

**Comment by fdodino** [comment]
Still does not work.

**Comment by fdodino** [comment]
I tested it: in dev mode, it doesn't work because you have to customize default accelerators in plugin.xml and activate shortcut in plugin_customization.ini, located in "org.uqbar.wollok.product" project. When you run in dev mode, product customization is not used. If you execute a mvn clean install from org.uqbar.wollok.releng project, and run generated product, it works. Haven't tested in Mac but it should work as pointed in http://cwd.dhemery.com/2008/06/rcp-keybindings/

**Comment by tesonep** [comment]
It is working!
