### ISSUE TITLE
Using a FQN for a class defined in another file compiles but then it cannot be resolved in runtime

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#346]
Sample

Main file having the issue

**a.wpgm**

``` xtend
program zuper {
        val pepona = new b.Golondrina()
}
```

Another file defines the class: 

**b.wlk**

``` xtend
class Golondrina  {
    method volar(kms) {
        console.println("flying...")
    }
}
```

This compiles fine (passes the validations), and also you can navigate the constructor call to the class Golondrina, but if you run the program you'll get something like

```
[ERROR] /Users/jfernandes/dev/data/repo/wollok-dev/wollok-tests/src/wollok/classes/super-program.wpgm:7:89 ERROR Couldn't resolve reference to WClass 'b.Golondrina'.
```

**Comment by tesonep** [comment]
This is not solved with the different folder wollok. As the other wollok files are never interpreted. In the test works because the files are not interpreted on demand. 

One solution I found is handling the FQN classes as implicit imports, as the other imports are handled. In the same way Java solves it. 

Other solution is to try to rewrite the scopes to look for a file when the scope does not have a qualified name. 

And the end solution is raising an error in the runtime. The grammar allows the FQN in class and mixin references. 

@fdodino @javierfernandes @npasserini what do you think?

**Comment by tesonep** [comment]
After talking with Fer, we decided to fix it making work. 
So you can reference a class or mixin with the FQN, this does not work for objects as the grammar is not allowing it. 
What I have done is to add an implicit import when I found a FQN class or mixin name.
This is done to make the runtime load the resources having the file, as the resources in the runtime are load on demand.

**Comment by fdodino** [comment]
You're big, Tesoun!

**Comment by npasserini** [comment]
OMG!

2017-07-11 17:25 GMT-03:00 Pablo Tesone <notifications@github.com>:
