### ISSUE TITLE
Invert assert.equals parameters?

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#401]
Although classical xUnit frameworks use `assert.equals(actual, expected)` syntax, at least in Spanish, users tend to write it flipped. I suppose this happens in other languages, since more modern assertion libraries, like `chai.js`  broke backward compatibility and actually changed that. 

So my proposal here is to change syntax to be  `assert.equals(expected, actual)`

**Comment by aitrusgit** [comment]
I think you wrote it backwards. Classical assertions are written in 'assert.equals(expected, actual)' style while chai.js uses 'assert.equals(actual, expected)' 

I kinda lean towards the classical approach since it focuses on determining first what you expect and then what you have (which fits nicely with my TDD idea). Having said that I do agree that it's often misleading and experience show that people tend to use it backwards. Maybe the question is: Is it matter of educating the user of designing the interface as the user will use it?

**Comment by flbulgarelli** [comment]
Jaja. There you see, i was a víctimas of my own issue. 

I think it is a matter of design interfaces that avoid frustration and follow the least surprise principle.
