### ISSUE TITLE
Replace extend keyword with subclass 

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#403]
Although Java derived languages tend to use `extend` keyword for subclassing, it is a misleading word. 

We don't use the term `extend` (extender) in our speech in initial OO courses. Instead, we use inherit, subclass, (heredar, subclasificar), since we usually reserve the meaning of extension to the fact of adding behavior to an existing object or class - using extension methods or open classes, for instance. 

So we have here an inconsistency between the language syntax and our speech. My suggestion here is to rename the `extend` keyword with `subclass` - or perhaps `inherit`

**Comment by npasserini** [comment]
I am not sure about subclass, it seems weird for me:

class Golondrina subclass Ave {}

Maybe we should write
class Golondrina subclass of Ave {}

Still does not fit too much

Inhterits feels a little better,

class Golondrina inherits Ave {}
or
class Golondrina inherits from Ave {}

Please note the final s of inherits. This is because I read it as a
declaration (a golondrina is a kind of ave) and not as an order (create a
class inheriting from ave). I prefer the declarative semantics and, well,
the keyword should reflect it.

**Comment by javierfernandes** [comment]
This is already merged into "dev". I guess we can already mark it as solved. It will be released in Wollok 1.3.0

**Comment by javierfernandes** [comment]
Closing it.
To be released with v1.3.0
