### ISSUE TITLE
Show object name in Outline window

### ISSUE THREAD

**Issue by sancuba** [uqbar-project/wollok#405]
ahora el objeto pepita:

object pepita {
	method volar() {
	// TODO
	}
}

aparece en Outline asi:
object
     volar()

De esta manera no puedo diferenciar objetos en Outline, salvo por el nombre de sus metodos

**Comment by javierfernandes** [comment]
Fixed in dev. 
Will be released with v1.3.0
If you are running the dev version then you can upgrade by using the dev update site url in your wollok IDE (see homepage for the URL)

<img width="120" alt="screen shot 2015-11-19 at 15 01 30" src="https://cloud.githubusercontent.com/assets/4428120/11279340/b184489c-8ece-11e5-87e6-66309def0979.png">
