### ISSUE TITLE
Use collection messages consistent with Haskell's Prelude

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#409]
The following collection messages are inconsistent with Haskell's Prelude

* `detect` -> `find`
* `exists` -> `any`
* `forAll` -> `all`

**Comment by javierfernandes** [comment]
I think that I prefer: anySatisfy instead of just "any" and allSatisfy instead of just "all"

I don't think we should just copy names for Haskell.
I think that their names in this case are not expressive enough.

Also maybe "findOne" instead of just "find". Because it does that, it finds just one, not all.

@npasserini  ?

**Comment by npasserini** [comment]
I agree that we should not just copy Haskell name, because I would like
that Wollok can be used in a wider context which includes students that not
necessarily know Haskell.

Any way, I never have been a fan of Smalltalk methods anySatisfy and
allSatisfy. On one hand they are long and I would like shorter names.
Moreover, I am pretty sure that "anySatisfy" is gramatically wrong, you
should say "anySatisfies" (see google translation bere:
https://translate.google.com/#es/en/cualquiera%20de%20estos%20elementos%20satisface%20la%20condici%C3%B3n
).

So I like any/all, and also they have a nice semantics (if you understand
english, of course).
Still, exists/forAll also have a nice mathematical background, so I do not
see a big issue on letting them live.

The biggest issue with forAll is the confusion with forEach, but maybe we
could change forEach instead, using each (like ruby) or do (like
smalltalk). Can you think of another nice names for this method?


Undoubtfully +1 to findOne instead of find (or detect).
Also, it makes me think of using find instead of filter.


Finally, after deciding all of this, we should probably rename curent any,
maybe to anyOne

**Comment by matifreyre** [comment]
I prefer clear messages, despite of being longer sometimes. I agree that anySatisfy is grammatically incorrect, but shortening it to "any" seems to me the opposite you are agreeing with when accepting findOne instead of find. My suggestion is the following:
- anySatisfies
- allSatisfy
- forEachDo (having 3 words makes me doubt about it... I can also stick to just "do" instead)
- findOne
- anyOne

**Comment by flbulgarelli** [comment]
I agree with changing any to `anyOne` , but I would like to point out that it is also grammatically wrong: it should be `anyone`, which actually means "no matter who". It is a whole word, not two. 

Regarding the other messages, I still think `any`/`all` are good names since when you have this code:

```groovy
planets.any { x => x.has_flowing_water()  } 
```
You read it as "do any of the planets have flowing water?"  - which is perfect valid English -, and not 
"do any of the planets satisfy the question of having flowing water" - which I am not sure is actually valid English, but in any case sounds horrible. 

The issue here is that Smalltalk incorrectly focuses on the block as whole, instead of focusing on its content.  They say "anySatisfy" because they are thinking whether any of the elements of the collection satisfy the block, which is OK from an implementation point of view, but not very friendly to the user point of view, where the important thing is the condition - in a higher level sense - and not the fact that is modeled as a block. 

Using all/any is not a very idiomatic Haskell issue, but quite standard: ruby, python, elixir and even c#

I proposed in this issue to use Prelude's names not because they are always great, but because they are easy to remember, fairly common and widely used across most modern industrial, languages. 

For example, I agree that forAll is expressive too, but I can't think of other language aside of Scala that implements that naming convention. By the way, `some`/`every` is the second more common, I think, being used by JavaScript and Clojure. But even many JavaScript libraries like Lodash have aliases from every to all and so on. 

The same applies to find - although I am not in love with the term - , it is broadly used instead of findOne: Haskell, Ruby, JavaScript (through libraries), Elixir, Scala, they all name it `find`. Naming it as `findOne` would cause that when students see `find` they would think that it will actually return a collection - which is true only for Mongo DSL as far as I know. And this is against the goal of a easy transition from Wollok. 

Regarding `each` vs `forEach` , I think there is no clear winner, both terms are quite common. 

Finally, I think that part of being expressive is being aligned with standards and not reinvent the wheel, as long as following the standards doesn't strongly collide with our speech - for example the extends vs inherits issue.  So my proposal is to not create custom unique wollok names - like `forEachDo`, please don't hate me @matifreyre :stuck_out_tongue_closed_eyes: -  unless we have a really really good cause.

**Comment by aguspina** [comment]
I agree in almost everything with @flbulgarelli except for one:

Personally I believe `forEach` is quite more expressive than just `each`.

**Comment by faloi** [comment]
I also agree with @flbulgarelli: our time is limited, and we should choose which battles we want to fight.

Perhaps Prelude's names aren't the best in terms of expressiveness, but they sure are the most standard among the community.

**Comment by faloi** [comment]
I also agree with @flbulgarelli: our time is limited, and we should choose which battles we want to fight.

Perhaps Prelude's names aren't the best in terms of expressiveness, but they sure are the most standard among the community.

**Comment by gastonprieto** [comment]
I agree in everything with @flbulgarelli :+1:

**Comment by javierfernandes** [comment]
@faloi well, being effective in terms of time/effort would have been to let them as they was ;)

**Comment by faloi** [comment]
@javierfernandes touché

**Comment by flbulgarelli** [comment]
I disagree here with the 'let at is is' point of view. 

We are taking about a collection API that is fully developed, on a language that is in its early development staged too, and is not widely used. If we can not alter syntax/semantics now, when will be able to do it?

And, if we will stick to initial decisions, and we are not able to adapt the language so that it better fits out speech an use cases, what is the point of having our own language instead of using an industrial one?

However, I also  disagree with @faloi comment haha. And it is by the same reason: refactoring a language is HARD: changing the interpreter, the tools, the documentation, the examples. And being an educative language it is even more true. This is one of the few cases where applying an iterative reasoning is not a so-great idea.

**Comment by flbulgarelli** [comment]
Fixed.
