### ISSUE TITLE
Add all objects the ability to notify errors

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#42]
Something like, in Smalltalk,
  self error: 'Something happen'

**Comment by javierfernandes** [comment]
This can be an inherited method from wollok.lang.Object

I suspect that this is priority since for the starting exercises we don't want to introduce exception handling and of course not classes (Exception) but we might still want them to cut the execution flow for particular situations. 
Also will avoid returning null and null-based conditions like if-null.

I wonder how this will impact our static check for consistent execution flow (return on all possible flow paths).

For example today it correctly checks throws:

```xtend

method inABlock4() {
		try {
			return 1
		}
		catch e : Exception {
			throw e
		}
	}
```

This compiles fine, and the method is considered to return a value on every flow (or throw an exception)

But what if we do this

```
method inABlock4() {
		try {
			return 1
		}
		catch e : Exception {
			this.handleError(e)
		}
	}

method handleError(e) {
     throw e
}
```

I think that it will complain because it's not recongnizing that the message send in the catch block is also cutting the flow.
I think that we can improve the check algorithm so that it analyses whether the message send will produce a throw, and then analyse the method if just has a single throw statement then we are fine.
Out of the scope
* More complex methods
* methods outside of this (in this case we first need to resolve the method, for which we need the type system)

What do you think ?

**Comment by npasserini** [comment]
Yes... but the same problem exists in any language that tries to check this
kind of things (Java, for example).
The easy work arround is to add a return to the handleError message send:

```

method inABlock4() {
        try {
            return 1
        }
        catch e : Exception {
            *return *this.handleError(e)
        }
    }

```

**Comment by tesonep** [comment]
The check is correct, I think adding the return is a problem, but is needed

For example if you extend the handleError doing something that do not stop
the flow, the check is ok. The checking could not know what you will do
ahead.

On Mon, Nov 16, 2015 at 9:55 AM, Nico Passerini <notifications@github.com>
wrote:

> Yes... but the same problem exists in any language that tries to check this
> kind of things (Java, for example).
> The easy work arround is to add a return to the handleError message send:
>
> ```
>
> method inABlock4() {
> try {
> return 1
> }
> catch e : Exception {
> *return *this.handleError(e)
> }
> }
>
> ```
>
>
> On Mon, Nov 16, 2015 at 9:37 AM, javierfernandes <notifications@github.com
> >
> wrote:
>
>
> > This can be an inherited method from wollok.lang.Object
> >
> > I suspect that this is priority since for the starting exercises we don't
> > want to introduce exception handling and of course not classes
> (Exception)
> > but we might still want them to cut the execution flow for particular
> > situations.
> > Also will avoid returning null and null-based conditions like if-null.
> >
> > I wonder how this will impact our static check for consistent execution
> > flow (return on all possible flow paths).
> >
> > For example today it correctly checks throws:
> >
> > method inABlock4() {
> > try {
> > return 1
> > }
> > catch e : Exception {
> > throw e
> > }
> > }
> >
> > This compiles fine, and the method is considered to return a value on
> > every flow (or throw an exception)
> >
> > But what if we do this
> >
> > method inABlock4() {
> > try {
> > return 1
> > }
> > catch e : Exception {
> > this.handleError(e)
> > }
> > }
> >
> > method handleError(e) {
> > throw e
> > }
> >
> > I think that it will complain because it's not recongnizing that the
> > message send in the catch block is also cutting the flow.
> > I think that we can improve the check algorithm so that it analyses
> > whether the message send will produce a throw, and then analyse the
> method
> > if just has a single throw statement then we are fine.
> > Out of the scope
> >
> > - More complex methods
> > - methods outside of this (in this case we first need to resolve the
> > method, for which we need the type system)
> >
> > What do you think ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/uqbar-project/wollok/issues/42#issuecomment-157015203>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uqbar-project/wollok/issues/42#issuecomment-157020743>
> .
>



-- 
Pablo Tesone.
tesonep@gmail.com

**Comment by javierfernandes** [comment]
Good point!

**Comment by javierfernandes** [comment]
Done !

```xtend
	class C {
		method foo() {
			this.error("Gently failling!")
		}
	}
```
