### ISSUE TITLE
Model NullReferenceException in wollok ??

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#433]
Do we have a better name ?  NullReferenceException ?

"Pointer" doesn't seem like a good concept.

Ideally we could model the null object ?
And have this case as a regular "MessageNotUnderstood: null does not understand blah()"

**Comment by npasserini** [comment]
I think it is better to diferentiate both situations, because in one case
you probably mispelled a message or you are talking so a different object
that you were expecting, and in the other case you most probably forgot an
initialization.

Modelling null as an object in a language which intends to (eventually)
have a type system is tricky if any reference can be null, because the null
object should have "Bottom" type and therefore understand any message (at
least from the typesystem point of view, I am not sure about the
implications in the runtime system).

Ja, maybe null should override doesNotUnderstand :P


Maybe the type system should asume that by default variables are not
nulleable and have a special modelling for the nulleable types (which also
has to be transparent for the programmer).

**Comment by fdodino** [comment]
I think although we didn't model NullReferenceException, we've enhanced good enough error messages related with null references. Closing it @npasserini
