### ISSUE TITLE
Add take/drop messages to collections

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#518]
It should work for bot lists and sets

**Comment by matifreyre** [comment]
Does the Set implementation have an order in its elements? Both messages, if considered as their respective Haskell functions, look like they should be implemented on List only because they do require order in the receiving collection. 
Let's suppose a set with the elements: 5, 1, 4, 8. What result do you expect from a query like aSet.take(2) ?

**Comment by javierfernandes** [comment]
Current Set is not sorted by any criteria.

**Comment by flbulgarelli** [comment]
The result of `take(n)` / `drop(m)` would not be ordered in a set, nor have any particular elements, just up to N element / N elements lesser. So:
 * they both share the semantics of taking / dropping a certain amount of elements
 * lists, in addition add the semantics of taking and dropping the initial elements

**Comment by flbulgarelli** [comment]
Makes it sense?

**Comment by npasserini** [comment]
I do not thinkg that take/drop make sense for sets.

**Comment by flbulgarelli** [comment]
Perhaps i drank too much kool aid. Let's implement it for lists only

**Comment by javierfernandes** [comment]
Solved by @J9794 and @JuanchiRios in 1be4833
