### ISSUE TITLE
Could wollok projects not be extensions of java projects?

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#6]
This makes us to have lots of dependencies and makes wollok runtime environment much heavier.

**Comment by javierfernandes** [comment]
This is heavy. Because the interpreter needs to xtext parser and all of its infrastructure to run.
On the other hand, if the language would be compiled into another kind of code (byte code, or even java code) then the runtime environment could be a plain old java app without any eclipse dependency.
But that's a huge change.

Maybe there's a way in between, but I'm not seeing it right now.

A workaround for this would be to customise the package view and hide all the java details from the wollok projects.
Of course this doesn't make it lighter. It's just to avoid implementation details to users.

**Comment by fdodino** [comment]
Lo marco como `Won't do` pero en realidad vamos camino a eso...
