### ISSUE TITLE
Error when declare var on other line: Enhance text

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok#663]
When you declare a var in an incorrect place (for example at the bottom of a class) it says "} missing" or something like that. It would be nice for it to say "vars should be declared at the begginning of the class"

**Comment by javierfernandes** [comment]
Yes, this makes sense.
Just writing a "technical description" to make it easier to fix later.

This is because the rule is implemented at "grammar-level". Wollok's xtext grammar defines that a class/object must first have all variables, then methods, etc.
So when writing a var in between methods the parser fails with that generic error.

I'm not sure it would be possible to fix this at parser level, or even customize the message.
The easiest solution is to:

- change the grammar so that it will accept methods/constructors/variables in any order. Like a collection of members
```
    members += ClassMember

ClassMember: Variable | Constructor | Method
```

And then have a static check rule (Validator method) that will check that all variables are declared first and if not then fail with the custom message Alf is mentioning.

The side-effect of this change is that it will make the check slower. Parser-level validations are faster than validator-level. But well,.. is the price :P
And we already have a lot of validator's checks so

**Comment by npasserini** [comment]
@javierfernandes I like your idea, but there are plenty of this kind of parser errors. So I wonder if it is possible to customize parser errors, because maybe in other cases it is not possible to solve it by just changing the grammar.

I've seen some posts in Internet that could help customizin parser error messages: https://tomkutz.wordpress.com/2013/06/13/xtext-customizing-error-messages-unordered-group/

**Comment by npasserini** [comment]
I think I've got a solution for this problem. Expected error reporting will be like this: 
```/* XPECT_SETUP org.uqbar.project.wollok.tests.xpect.WollokXPectTest END_SETUP */
class Golondrina {
	// XPECT errors --> "Couldn't resolve reference to Referenciable 'energia'." at "energia"
	method energia() = energia
	
	// XPECT errors --> "You should declare variables before constructors and methods."
	var energia = 0
}

```
