### ISSUE TITLE
"EOF" parser error message when declaring a class after below a program

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#683]
Although the following program is valid: 

import pepita2.*

``` wollok
class Pepita {

}

program abc {
    new Pepita().comer()
    console.println('Hello Wollok')
}
```

the following is not: 

``` wollok
program abc {
    new Pepita().comer()
    console.println('Hello Wollok')
}

class Pepita {

}
```

You get: 
-  `missing EOF` at the Pepita class declaration
  -  and, not surprisingly, you get an `couldn't resolve reference Pepipta` in the constructor usage.  

This means that program declarations are order aware, unlike classes declarations, that are aren't.

**Comment by npasserini** [comment]
The second program is not valid, program should come after classes, we
"encourage" that.
Still... the error message could be better.

**Comment by flbulgarelli** [comment]
> The second program is not valid, program should come after classes, we
"encourage" that.

Why?

> Still... the error message could be better.

OK, so the problem is the error message.

**Comment by tesonep** [comment]
The problem is with the parser, because after a Program element the only viable element is the EOF, I don't know how to fix that maybe @javierfernandes , or we have to dive in the xtext docs and code.

**Comment by npasserini** [comment]
On Wed, Jun 8, 2016 at 2:05 AM, Franco Leonardo Bulgarelli <
notifications@github.com> wrote:

> The second program is not valid, program should come after classes, we
> "encourage" that.
>
> Why?
>

I am not sure that I would poot a foot on this, but I think that it is a
nice feature that the language helps you organice your program, disallowing
bad options.

Yet, maybe your example could be accepted, so we could have two options:
class* - program (could be thought as specific-to-generic = s2g)
or
program - class* (g2s)

I think that
class* - program - class* is not a good option and should be forbidden.

This is the same reason why we have three types of files, to force you
organice your tests in a different file and to start recognising that test
code should not be mixed with "application"/domain code.


Still, even when we could accept s2g *and* g2s, I think that for beginners
it is good to see patterns, and putting the program always in the same
place is helpful. Selecting the beginning or the end of the file is
secondary, but having only one option might be better than having two.

Also I think that Gobstones enforces putting *program *at the end, doesn't
it?


As a lateral thought, the idea is that we shouldn't use programs unless we
are working with wollok game, because otherwise we are forced to work with
console outputs, which is something we are trying to escape from.

**Comment by javierfernandes** [comment]
Not sure how to customize that message.
Seems like a really low level one.

**Comment by javierfernandes** [comment]
Related to #350

**Comment by fdodino** [comment]
Changed error message to: "Bad structure: class definition must be before program" (it should be generic enough, will be testing these days).
Added some tests: OrderConstructionParserTest in branch "parser-messages".

**Comment by fdodino** [comment]
![issues683.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/576a9edc38c9e40e00848c20/125516c66e82c728ace21e0d46e18789368790ffd7bafd0fe64de29b234324676b5ee17e25d6b42eba447957570e4cf8175d0944fcab8c2cf4bf6d62964e49bc8f3900299f7744eeaa880dbe07b0218e4f80b1ba8e4cc1ea3523e199c2.png)
