### ISSUE TITLE
Wollok Eclipse memory consumption

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#723]
When wollok starts, it consumes ~750MiB. After using it for an hour or so, it consumes more than 1GiB.

![wollokscreenshot](https://cloud.githubusercontent.com/assets/677436/15939206/1a7a3082-2e4d-11e6-8c0f-9e9b2f237537.png)

This is far more than the 40-100MiB memory consumption of Pharo. 

Is it bad? In a medium machine with > 4GiB, no, it is ok - while writing I have a 600MiB Chromium Tab opened - but in low resources machine, this is a big issue. For example, I have had and I currently have several students whose main or only computer is an old Conectar Igualdad 1GiB machine that got in high school. Even new models have just 2GiB - http://www.conectarigualdad.gob.ar/seccion/netbook/descripcion-los-equipos-56 -. 

Thus, I believe reducing the memory consumption of an educative tool is really important

**Comment by fdodino** [comment]
How many projects opened did you have?

http://stackoverflow.com/questions/1490803/how-to-reduce-eclipses-memory-usage
Maybe we can uninstall spell checker, and several plugins for "users" IDE

**Comment by fdodino** [comment]
Also this
http://stackoverflow.com/questions/316265/how-can-you-speed-up-eclipse
"Another performance boost can be gained by disabling label decorations (Windows -> Preferences; General -> Appearance -> Label Decorations) and by disabling unused capabilities on startup (Windows -> Preferences; General -> Startup and Shutdown)."

From http://www.nicolasbize.com/blog/7-tips-to-speed-up-eclipse/
Tip 2 : Tune Eclipse Preferences
General > Startup and Shutdown : remove all plugins activated on startup
General > Editors > Text Editors > Spelling : Disable spell checking
General > Validation > Suspend all
Window > Customize Perspective > Remove stuff you don’t use or want (shortcut keys are your friends), same for Menu Visibility (how many times have you printed a source file…)
Install/Update > Automatic Updates > Uncheck “Automatically find new updates”
General > Appearance > Uncheck Enable Animations
Stay with the default theme. Unfortunately, anything else makes it really laggy and slow.

I personally turn off autosuggestions so that they don’t slow down my typing. Instead, I manually trigger the auto suggestions using Ctrl+Space when needed. This is done through:

Java > Editor > Content Assist > disable Enable Auto Activation. Advanced > Remove all unwanted kinds

Some of this recommendations I don't agree.

**Comment by flbulgarelli** [comment]
Hi @fdodino.  I had just one nearly empty project.

**Comment by fdodino** [comment]
What do you think @npasserini ? After a year, I could see running Wollok was no big deal even in netbooks.

**Comment by fdodino** [comment]
Closing this issue since no great problems were reported.
