### ISSUE TITLE
Should Collection's method absolute(closure, criteria) return null or just fail for empty collections?

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#724]
This method has no doc at all. It's being used for min(closure) and max(closure), which I think should fail, but I'm not sure if absolute has a more generic purpose.
Related to the discussion in #718, where I'd need to throw an exception for empty collections on the forementioned methods, I don't know if I can do it directly within the absolute method or I should do it outside.

**Comment by flbulgarelli** [comment]
I vote for throwing an exception. Returning nulls is largely considered a bad design practice unless clearly stated the contrary on the method signature

**Comment by iluetich** [comment]
Hi! My 2 cents: i really do prefer to throw an exception, as stated by @flbulgarelli. Having to check whether a call returned **null** or not is really painful, annoying and prone to forget.

Although it's a more different situation than a **find()** where you could even pass a default value in case it didn't succeed, the **min()** and **max()** are methods that rely on the fact that there is an element in this set of objects that are _superior_ or _inferior_ in some aspect than others. In an empty collection, this doesn't make sense given there are no elements to make a comparison. 

Now, on the other hand, as @matifreyre states, **absolute** method do seems to be for general purposes. So, maybe the discussion should be towards finding a particular situation where returning **null* is a bad/good idea in empty collections, and generalise as much as possible the same behaviour on the largest amount of particular situations.

**Comment by matifreyre** [comment]
>Now, on the other hand, as @matifreyre states, absolute method do seems to be for general purposes. So, maybe the discussion should be towards finding a particular situation where returning *null is a bad/good idea in empty collections, and generalise as much as possible the same behaviour on the largest amount of particular situations.

Please note that within _wollok.wlk_, the only place where this **absolute** method is used is in **min(closure)** and **max(closure)**, therefore guiding me to think that it's just an auxiliary for those.

**Comment by iluetich** [comment]
> Please note that within wollok.wlk, the only place where this absolute method is used is in min(closure) and max(closure), therefore guiding me to think that it's just an auxiliary for those.


Ok. Then, i guess it makes it even better to throw an exception. Given **absolute** method takes a transformation and a comparator, if it has no elements to operate with, i think it should be expected to throw an error rather than returning a **null** (How can i determine the maximum / minimum in a set of elements if it is empty?).
Some other languages's approach on the matter:
- **Haskell** gives an Exception stating it's an empty list whether it is **[minimumBy](https://www.haskell.org/hoogle/?hoogle=minimumBy)** or **[maximumBy](https://www.haskell.org/hoogle/?hoogle=maximumBy)**.
- **Java** throws an exception if there are no elements in **[min](http://www.tutorialspoint.com/java/util/collections_min_comparator.htm)** and **[max](http://www.tutorialspoint.com/java/util/collections_max_comparator.htm)**.
- **Scala** interprets the result using the monad **[Option](http://www.tutorialspoint.com/scala/scala_options.htm)** (analogue to Haskell's Maybe) having the result of the operation be **Some** element or **None**. Although **None** would be the high-level representation of **null**, it exposes an interface to keep chaining operations without having the _null-check_.

**Comment by npasserini** [comment]
Agree, should throw an exception.

**Comment by matifreyre** [comment]
Changed on #718
