### ISSUE TITLE
Collections equality not working properly

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#743]
I think it's testing the elements for identity instead of testing for equality. You can see that ```assert.equals('Hello', 'Hello')``` passes, while ```assert.equals(['Hello'], ['Hello'])``` fails. These are lists, but the same happens with sets, while it doesn't happen when the elements are numbers.

**Comment by fdodino** [comment]
It works for collection of numbers.
That's because Lists contains WollokObjects. So equals fails for Strings and other non-cached values, I suppose.

**Comment by fdodino** [comment]
Solved in local commit, now

- two lists are equals if they hold the same native objects in the same order, based on wollokEquals rather than ==
- two sets are equals if they contain same objects, no matter which order
- i'll define also an equality method for Dictionaries, in their own branch

Should I push this into dev-collections-api or should I generate a new branch?

**Comment by matifreyre** [comment]
This is a bug fix, I'd rather have it merged immediately. That branch (PR
#744) is not so urgent, as it contains a bunch of enhancements. Having said
that, I think that that branch could be merged now that you fixed the tests
;-)
