### ISSUE TITLE
Localization of IDE

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#86]

**Comment by javierfernandes** [comment]
http://eclipse.org/articles/Article-Internationalization/how2I18n.html ?

**Comment by javierfernandes** [comment]
I have followed this tutorial
http://www.vogella.com/tutorials/EclipseInternationalization/article.html

Basically there are two mechanisms for i18n:
- for plugin.xml files there's a "plugin.properties" file in each plugin
- for code strings, there's a "messages.properties" file within the code in each project, in the root package.

To externalize plugin.xml, you just need to:
- replace the text un plugin.xml with a key starting with the % symbol. Example "%wizardTitle"
- then place a key = value in plugin.properties. Ex:   "wizardTitle  = New Wizard"

Also notice that this is an OSGI mechanism, so the default file name resolution (to resolve the plugin.properties) doesn't use "plugin.properties" (it uses something like "OSGI-INF/l10n/bundle"

So to customize that we need to specify a property in META-INF/MANIFEST.MF

```
Bundle-Localization: plugin
```

That's all.

Then there's the code i18n.
For that I used eclipse. 

1. right click on "src" folder of a project
2. Source -> Externalize Strings
3. Then go through all the detected files and for each
4. Check the strings you want to localise
5. Assign a better key (on the second column)
6. Choose below a configuration to reuse the same Messages.java class and message.properties file. Otherwise it will create a new class and file for each of you java class. That would be overkill.

We try to use a single messages.properties file.

So, this mechanism uses a generated class with static fields to avoid strings.
Example usage:

```
MessageDialog.openError(getShell(), Messages.AbstractNewWollokFileWizard_errorTitle, realException.getMessage());
```

Example working i18n

![screen shot 2015-05-23 at 11 38 40](https://cloud.githubusercontent.com/assets/4428120/7784608/f041c4c6-0141-11e5-8b39-83202f840c68.png)


Then if while developing you want to start the eclipse in an specific language, edit the run configuration.
Then specify there a locale with the "nl" argument

![screen shot 2015-05-23 at 11 51 16](https://cloud.githubusercontent.com/assets/4428120/7784611/0e8b8f70-0142-11e5-8c6b-88706d70adc5.png)

**Comment by javierfernandes** [comment]
I think that there's currently no support for the eclipse i18n view for xtend files :(
So currently we need to externalise xtend files manually, creating a new constant in the Messages class and file.

**Comment by javierfernandes** [comment]
i18nizing code templates

![screen shot 2015-05-23 at 12 25 41](https://cloud.githubusercontent.com/assets/4428120/7784736/f003006a-0146-11e5-8718-fa408281c7e1.png)

**Comment by javierfernandes** [comment]
i18nizing quick fixes

![screen shot 2015-05-23 at 12 46 48](https://cloud.githubusercontent.com/assets/4428120/7784813/d92c29d6-0149-11e5-96ca-60903c5f6959.png)

There are still many of them to i18n in 

```WollokDslQuickfixProvider```

The thing is that we need to do it manually because it is xtend code :(
Really painful.
I'll create a new issue for this.
