### ISSUE TITLE
When an object doesn't understand a message the error should say so 

### ISSUE THREAD

**Issue by gcrespi** [uqbar-project/wollok#878]
![img_20160801_101555441_hdr](https://cloud.githubusercontent.com/assets/10291211/17295194/44eb8ee2-57fb-11e6-96f3-b4c8e34ce8f9.jpg)

**Comment by gcrespi** [comment]
It shouldn't use the word "method" instead

**Comment by javierfernandes** [comment]
This is the error reported by the static code analyser. The message was not
even sent.
If you try to send this message to a variable different than the name of an
WKO then you will see something like "MessageNotUnderstood" which is the
runtime check for this.

As part of providing more static checks to catch potential programming
errors, even if we don't have a type system we are checking some simple
clases like WKO.
In particular when you use the name of the WKO we can statically know which
messages it understand so we can check them.

I'm telling this because it may make it clear that in this case, the error
message is actually right ! We statically know that the WKO doesn't have
any method to respond to that message.

Anyway, we can change it to use "message" instead of method.

**Comment by flbulgarelli** [comment]
I think that the problem may be other: perhaps we should not run static checks on the repl. It is kinda weird that the error messages are so different if you send an unkown message to a WKO or to another reference. 

The goal of many of static checks is to prevent errors before they occur. Since we are already executing the code "live", preventing the execution has little sense. 

I guess that could avoid the effort of replicating the messages of runtime errors in static checks in order to reduce surprise

**Comment by npasserini** [comment]
On Mon, Aug 1, 2016 at 7:34 PM, Franco Leonardo Bulgarelli <
notifications@github.com> wrote:

> I think that the problem may be other: perhaps we should not run static
> checks on the repl. It is kinda weird that the error messages are so
> different if you send an unkown message to a WKO or to another reference.


We could try, but (we have already discussed this) you should always
remember that static errors include lots of stuff, such as linking... so
trying to run code with linking errors can produce extremely weird error
messages, because you are running an inconsistent program. Even more...
executing a program with syntax errors... has undefined and unknown
behavior.

It might not be this case, you can try to send any message to any object,
but if you execute "2 + whateverUnexistentVariable" and you do not stop the
executiion when you detect that the variable does not exist... I do not
know what is what the + method will receive as an argument.

Yes ... we could improve that, but it is far from trivial to be able to
execute inconsistent ASTs. I would prefer to first think if there isn't a
better way to show static errors in the repl, if we know the program is
wrong... why not tell the user instead of letting him beat his own fingers?

**Comment by javierfernandes** [comment]
I actually tried to show static errors as highlighted on the input text.
But it is not fully working. Some parsing errors are being shown as red
text. For example while you are typing a list literal if you type something
like

[ 1, 2,   ]

It will show it red.

This should be improved maybe even disabling sending the input to de repl
if it has errors. We also need some kind of automatic tooltip with the
errror message. Or a feedbak area to show the message.

**Comment by flbulgarelli** [comment]
> We could try, but (we have already discussed this) you should always
remember that static errors include lots of stuff, such as linking... so
trying to run code with linking errors can produce extremely weird error
messages, because you are running an inconsistent program. Even more...
executing a program with syntax errors... has undefined and unknown
behavior.

OK. And what about something in the middle? Perhaps we could just ignore those errors that are not critical, and keep errors that actually signal an invalid program.

Which are those errors? `Syntax`? `Linking`? Both?

**Comment by javierfernandes** [comment]
Fixed ! See the updated test file for the new message.
