### ISSUE TITLE
Asserting double numbers with error margin

### ISSUE THREAD

**Issue by tsandler** [uqbar-project/wollok#905]
It would be good if we could test with an assert that rounds or truncate the actual number in order to match the expected one.

For example:

``` xtend
assert.equalsRounded(1.444555666,1.444555666777)
```

**Comment by PalumboN** [comment]
Related to https://github.com/uqbar-project/wollok/issues/862

**Comment by matifreyre** [comment]
You would need to tell the requested accuracy too (how many decimals should
it compare).

**Comment by tsandler** [comment]
Could we have two methods, one with a default value and the other one sending the accuracy as parameter?

**Comment by matifreyre** [comment]
Yeees... we certainly could, but I don't see the point of it. I mean, there is no "most used" value for the number of decimals in a floating point representation, you would be choosing an arbitrary one.

Let put some business examples:
* An acountant would probably choose 2 decimals because amounts usually use that number (e.g. $ 3.55) 
* A warehouse manager could choose 3 decimals because quantities use that (e.g. 4.300 Kg.). 
* Someone in the pharmaceutical industry may choose 4 because his/her formulas requiere more precision (0.6570 grams).

**Comment by tsandler** [comment]
I think 2 is the most used, but I see your point and I agree. It would be very useful if we could have at least one assertion method with an accuracy number

**Comment by fdodino** [comment]
Don't know if it is useful, now you have 3 methods for decimals

```scala
	/**
	 * Answers the next integer greater than self
	 * 13.224.roundUp() ==> 14
	 * 15.942.roundUp() ==> 16
	 */
	method roundUp() = self.roundUp(0)
	
	/**
	 * Rounds up self up to a certain amount of decimals
	 * 1.223445.roundUp(3) ==> 1.224
	 * 14.6165.roundUp(3) ==> 14.617
	 */
	method roundUp(_decimals) native
	
	/**
	 * Truncates self up to a certain amount of decimals
	 * 1.223445.truncate(3) ==> 1.223
	 * 14.6165.truncate(3) ==> 14.616
	 */
	method truncate(_decimals) native
```

**Comment by npasserini** [comment]
It can de done, but maybe temporarily.
In the long run, I think that we should avoid these precision problems. The
necessity for that precision argument comes from the inherent IMprecision
from floating point numbers... which we do not use.

So it is necessary?
I would like to see examples of tests that can't be expressed with the
actual tools.

**Comment by npasserini** [comment]
I think that this can be solved using @fdodino 's idea.

For example:
```
test "test truncation" {
	assert.equals(0.333, (1/3).truncate(3))
}
```

What do you think? @PalumboN @matifreyre

**Comment by PalumboN** [comment]
:+1:
