### ISSUE TITLE
Tests exception messages are inverted

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/wollok#928]
when tests fails, values are inverted in relation of labels 

for example
```xtend
test "Carlos cobra 600 en total por pintar 20 metros" {
	assert.equals(carlos.costo(20),600)
}
```

carlos.costo(20) returns 500 so, test fails

but the message is
`wollok.lang.Exception: Expected [500] but found [600]`

should be
`wollok.lang.Exception: Expected [600] but found [500]`

**Comment by matifreyre** [comment]
This one was already discussed a couple of months ago... it's not wrong,
the message is correct. The syntax is:
assert.equals(expectedValue, actualValue)

**Comment by flbulgarelli** [comment]
> This one was already discussed a couple of months ago... 

Did we actually conclude something about it? I think not, since this issue is still open...

https://github.com/uqbar-project/wollok/issues/401

**Comment by matifreyre** [comment]
By lack of any further discussion, I assumed that we would keep the current syntax. Other languages I know use Wollok's current order of parameters.
Anyway... in my opinion, this issue is OK to be closed, as the message is consistent with the current implementation and wollokdoc, while #401 can be discussed further all you want and possibly lead us to decide to invert the order.

**Comment by flbulgarelli** [comment]
@matifreyre you are right. This issue is ok to be closed since it is consistent with current goal. 

Regarding the order issue, let's discuss it in the other thread.
