### ISSUE TITLE
allow multivar declarations and assignments

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#94]
For example

``` scala
class Point {
     var x, y
}

 var x = 1, y = 2

```

Or a different syntax

``` scala
var x, y = 1, 2
```

**Comment by flbulgarelli** [comment]
I personally don't like such flexibility, since it allows two different ways of doing the same thing, and that leads to having to set conventions about when to use which form. 

*But* my opinion would change if we are thinking this as par of a deconstruction  - aka destruction - feature, which is a previous milestone in the way of pattern matching. 

Eg: 

```
var (x, y) = (1, 2)  //assuming we have a tuple type
var [x, y] = [1, 2]
var [x|xs] = [1, 2]
var [_, y] = [1, 2]
var {foo: x, baz: [y, z]} = {foo: 4, baz: [2, 3]}
//and so on
```

**Comment by fdodino** [comment]
Stale issue, no sponsors => I think we can close it and try to discuss it if anyone is interested.
